name: Automatic Semantic Release

on:
  # workflow_dispatch # manual-only for testing
  push:
    branches: 
      - main 
jobs: 
  new-release: 
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Checkout our working repository
        with: 
          github-token: ${{ secrets.GH_TOKEN }} 
          output-file: "false" 
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v4
        with:
          github-token: ${{ secrets.GH_TOKEN }}
      - name: Create Release # This action will create the actual release 
        uses: actions/create-release@v1 
        if: ${{ steps.changelog.outputs.skipped == 'false' }} 
        env: 
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} 
        with: 
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }} 
          body: ${{ steps.changelog.outputs.clean_changelog }}

 
